### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by 3kh0** [CycloneHacks/CycloneHacks.github.io#1]
Hello there!

I have looked through your GitHub repo and I found some things that I believe were taken from my site. I ask that you take them down to respect my work and what I do.
If the original one was blocked then you can contact me and I can give you more links. If you have any questions please feel free to reach out to me!

Thanks!
Echo

**Comment by CycloneHacks** [comment]
Oh yes sorry it's that their is this other person who has the same things
and website as you. But yes I get it. Can you pls give me links to other
games?

**Comment by smileman52** [comment]
Fixed
