### ISSUE TITLE
Grounded

### ISSUE THREAD

**Issue by CycloneHacks** [CycloneHacks/cyclonehacks.github.io#9]
HELPPPPPPPPPPPPPPPPPPPP SMILEMAN IM DYING

**Comment by smileman52** [comment]
why?

**Comment by CycloneHacks** [comment]
Dude we need to talk in here now :((... I got grounded and stuff. Need u to check on here for a while for important things Rn im using a proxy. Btw you didnt like the red?? on the clock??

**Comment by CycloneHacks** [comment]
Btw Email me using your Personal computer or School Computer At : 2027reyesfernandez.brian@fcboe.org.
Sadly cant use my other email :((

**Comment by smileman52** [comment]
rippp
